package com.example.report

import android.content.ContentValues
import android.content.Context
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import com.example.data.Transaction
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Cell
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.element.Table
import com.itextpdf.layout.properties.TextAlignment
import com.itextpdf.layout.properties.UnitValue
import java.io.File
import java.text.NumberFormat
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class PdfGenerator(private val context: Context) {

    fun generateReport(
        transactions: List<Transaction>,
        periodTitle: String,
        totalAmount: Long
    ): File {
        val dateFormat = SimpleDateFormat("yyyy-MM-dd_HH-mm-ss", Locale.getDefault())
        val fileName = "Kiseh_Report_${dateFormat.format(Date())}.pdf"

        // 1. فایل اولیه در پوشه عمومی Kiseh برای دسترسی کاربر
        val appPdfDir = File(context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS), "Kiseh").apply {
            if (!exists()) mkdirs()
        }
        val appFile = File(appPdfDir, fileName)

        val writer = PdfWriter(appFile)
        val pdf = PdfDocument(writer)
        val document = Document(pdf)

        // Title
        val title = Paragraph("Kiseh Expense Report / گزارش هزینه های کیسه")
            .setTextAlignment(TextAlignment.CENTER)
            .setFontSize(20f)
            .setBold()
        document.add(title)

        document.add(Paragraph("\n"))

        // Period info
        document.add(Paragraph("Period / دوره: $periodTitle").setFontSize(14f))
        document.add(
            Paragraph("Total Expenses / مجموع هزینه ها: ${formatMoney(totalAmount)} Toman")
                .setFontSize(14f)
                .setBold()
        )

        document.add(Paragraph("\n"))

        // Category breakdown table
        val categoryTotals = transactions
            .filter { !it.isIncome }
            .groupBy { it.category }
            .mapValues { entry -> entry.value.sumOf { it.amount } }

        val categoryTable = Table(UnitValue.createPercentArray(floatArrayOf(40f, 40f, 20f)))
        categoryTable.setWidth(UnitValue.createPercentValue(100f))

        // Table Header
        categoryTable.addCell(Cell().add(Paragraph("Category / دسته").setBold()))
        categoryTable.addCell(Cell().add(Paragraph("Amount / مبلغ").setBold()))
        categoryTable.addCell(Cell().add(Paragraph("Percent / درصد").setBold()))

        categoryTotals.forEach { (category, amount) ->
            val percentage = if (totalAmount > 0)
                (amount.toFloat() / totalAmount * 100).toInt()
            else 0

            categoryTable.addCell(Cell().add(Paragraph(category)))
            categoryTable.addCell(Cell().add(Paragraph(formatMoney(amount))))
            categoryTable.addCell(Cell().add(Paragraph("$percentage%")))
        }

        document.add(categoryTable)

        document.add(Paragraph("\n"))

        // Transactions table
        val transactionsTable = Table(UnitValue.createPercentArray(floatArrayOf(25f, 35f, 20f, 20f)))
        transactionsTable.setWidth(UnitValue.createPercentValue(100f))

        // Table Header
        transactionsTable.addCell(Cell().add(Paragraph("Date / تاریخ").setBold()))
        transactionsTable.addCell(Cell().add(Paragraph("Description / شرح").setBold()))
        transactionsTable.addCell(Cell().add(Paragraph("Category / دسته").setBold()))
        transactionsTable.addCell(Cell().add(Paragraph("Amount / مبلغ").setBold()))

        val displayDateFormat = SimpleDateFormat("yyyy/MM/dd", Locale.getDefault())

        transactions.forEach { transaction ->
            val date = displayDateFormat.format(Date(transaction.date))

            transactionsTable.addCell(Cell().add(Paragraph(date)))
            transactionsTable.addCell(Cell().add(Paragraph(transaction.description)))
            transactionsTable.addCell(Cell().add(Paragraph(transaction.category)))
            transactionsTable.addCell(Cell().add(Paragraph(formatMoney(transaction.amount))))
        }

        document.add(transactionsTable)

        document.add(Paragraph("\n\n"))
        document.add(
            Paragraph("Generated by Kiseh Application / تولید شده توسط اپلیکیشن کیسه")
                .setTextAlignment(TextAlignment.CENTER)
                .setFontSize(10f)
        )

        document.close()

        // 2. ذخیره مستقیم فایل در پوشه Kiseh در حافظه گوشی (Documents/Kiseh و Download/Kiseh)
        saveToPublicKisehStorage(appFile, fileName)

        return appFile
    }

    private fun saveToPublicKisehStorage(sourceFile: File, fileName: String) {
        try {
            // ایجاد پوشه Documents/Kiseh
            val docsFolder = File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS), "Kiseh").apply {
                if (!exists()) mkdirs()
            }
            val docsTarget = File(docsFolder, fileName)
            sourceFile.copyTo(docsTarget, overwrite = true)

            // ایجاد پوشه Download/Kiseh
            val downloadFolder = File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), "Kiseh").apply {
                if (!exists()) mkdirs()
            }
            val downloadTarget = File(downloadFolder, fileName)
            sourceFile.copyTo(downloadTarget, overwrite = true)

            // ثبت در MediaStore برای اندروید ۱۰ و بالاتر
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                val contentValues = ContentValues().apply {
                    put(MediaStore.MediaColumns.DISPLAY_NAME, fileName)
                    put(MediaStore.MediaColumns.MIME_TYPE, "application/pdf")
                    put(MediaStore.MediaColumns.RELATIVE_PATH, "${Environment.DIRECTORY_DOWNLOADS}/Kiseh")
                }
                val uri = context.contentResolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, contentValues)
                uri?.let {
                    context.contentResolver.openOutputStream(it)?.use { outputStream ->
                        sourceFile.inputStream().use { inputStream ->
                            inputStream.copyTo(outputStream)
                        }
                    }
                }
            }
        } catch (_: Exception) {
            // Ignore if OS blocks public folder write
        }
    }

    private fun formatMoney(amount: Long): String {
        return NumberFormat.getNumberInstance(Locale("fa", "IR")).format(amount)
    }
}

